### ISSUE TITLE
resend token

### ISSUE THREAD

**Issue by yotavm** [florianheinemann/passwordless#104]
hey,
how i  resend the token ?

**Comment by florianheinemann** [comment]
Should the resend be triggered by the user or you? In case of the user he simply has to login once more. If it's you (e.g., a reminder) I would probably make a "fake" call to the `requestToken` middleware. This will update the token and resend the email

**Comment by yotavm** [comment]
hey  im using your lib for api to app so i dont work with render and stuff like this
and so is hard to look on the eamples 
i have on last think how i know after calling acceptToken if the token is good or not

**Comment by florianheinemann** [comment]
You could simply look for HTTP 401 returns on restricted URLs, or?

**Comment by yotavm** [comment]
i see that on token not verified you return string to the next  is true ?
so i can use this or fork and modify to return object with true or false?

**Comment by florianheinemann** [comment]
That's surely possible but seems to be asking for trouble. This is a HTTP-based authentication framework. You will anyway have to deal with 401 messages when conducting API transactions

**Comment by yotavm** [comment]
only if i using the restrict function
or acceptToken send 401 ?

**Comment by florianheinemann** [comment]
Well - generally for all requests your app should be apple to deal with the different HTTP status codes (e.g., 500, 404, 401, ...). It's not just about accepting token. Imagine you add later functionality to block a user after he has been signed in due to suspicious behavior. You want to make sure that you can simply block all future requests by sending 401s
